version: 0.2

env:
  variables:
    REGION: ap-northeast-1

phases:
  build:
    commands:
      - sam build
      - >-
        sam deploy
        --stack-name stack-sgp-${ENV}-backend-main
        --no-confirm-changeset
        --no-fail-on-empty-changeset
        --resolve-s3
        --parameter-overrides Env=$ENV
        --capabilities CAPABILITY_NAMED_IAM
        --region ${REGION}
